development:
  adapter: postgresql
  encoding: unicode
  database: sampi_capapp_development
  username: sampi
  password: sampi.123
  host: 127.0.0.1
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: sampi_capapp_production
  username: sampi
  password: sampi.123
  host: postgresql1.alwaysdata.com
  port: 5432